AssetHealth/Models/Device/DeviceModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Ares.UMS.DTO.Security;
using Ares.UMS.DTO.Users;
using Ares.Web.Models;
using Ares.Web.Razor;
using System.Web.Mvc;
using FluentValidation.Attributes;
using AssetHealth.Validators;
using AssetHealth.Common.DTO.Enums;
using Ares.Web.Extensions;
using Ares.Sync.DTO.Enums;
using Ares.Sync.Controllers;
using Ares.Web.JSON;
using Newtonsoft.Json;

namespace AssetHealth.Models.Device
{
    [Validator(typeof(DeviceModelValidator))]
    public partial class DeviceModel : BaseAresModel //, ILocalizedModel<TopicLocalizedModel>
    {
        public DeviceModel()
        {
            //Locales = new List<TopicLocalizedModel>();
            SelectedTab = "1";
            
            Filter_FormAnswerModel = new AssetHealth.Models.Form_answer.FormAnswerModel();  
                       
            
            Filter_FormAnswerRoundModel = new AssetHealth.Models.Form_answer_round.FormAnswerRoundModel();  
                       
            
            Filter_SynchronizationModel = new AssetHealth.Models.Synchronization.SynchronizationModel();  
                       
            
            Filter_SynchronizationDeviceModel = new AssetHealth.Models.Synchronization_device.SynchronizationDeviceModel();  
                       
            
            Filter_SynchronizationLogModel = new AssetHealth.Models.Synchronization_log.SynchronizationLogModel();  
                       
        }
        
        public string SelectedTab { get; set; }

        
        [AresResourceDisplayName("DeviceModel.Fields.Id")]
        public int Id { get; set; }
        

        
        [AresResourceDisplayName("DeviceModel.Fields.Device_type")]
        public EnumDeviceDevice_type? Device_type { get; set; }
        
        public virtual string EnumDevice_type_Text
		{
			get 
            { 
                return EnumExtensions.ToLocalizedtring(Device_type);
            }
		}
        
        
        [AresResourceDisplayName("DeviceModel.Fields.Udid")]
        public string Udid { get; set; }

        [AresResourceDisplayName("DeviceModel.Fields.Imei_number")]
        public string Imei_number { get; set; }



        [AresResourceDisplayName("DeviceModel.Fields.Device_name")]
        public string Device_name { get; set; }
        
        
        
        [AresResourceDisplayName("DeviceModel.Fields.Device_model")]
        public string Device_model { get; set; }

        [AresResourceDisplayName("DeviceModel.Fields.Package_info")]
        public string Package_info { get; set; }

        public List<AutoUpdateEntity> AutoUpdateEntities { get; set; }

        [AresResourceDisplayName("DeviceModel.Fields.AssetHealth_Version")]
        public string AssetHealth_Version
        {
            get
            {
                AutoUpdateEntities = AutoUpdateEntities == null && !string.IsNullOrEmpty(Package_info) ? JsonConvert.DeserializeObject<Ares.Web.Mvc.Entities.BaseRequest<List<AutoUpdateEntity>>>(Package_info, new AresJsonSerializerSettings()).Data : AutoUpdateEntities;

                if (AutoUpdateEntities != null && AutoUpdateEntities.Exists(e => !string.IsNullOrEmpty(e.appname) && e.appname.Contains("com.improvative.assethealth")))
                    return AutoUpdateEntities.FirstOrDefault(e => !string.IsNullOrEmpty(e.appname) && e.appname.Contains("com.improvative.assethealth")).version;

                return "";
            }
        }

        [AresResourceDisplayName("DeviceModel.Fields.TechService_Version")]
        public string TechService_Version
        {
            get
            {
                AutoUpdateEntities = AutoUpdateEntities == null && !string.IsNullOrEmpty(Package_info) ? JsonConvert.DeserializeObject<Ares.Web.Mvc.Entities.BaseRequest<List<AutoUpdateEntity>>>(Package_info, new AresJsonSerializerSettings()).Data : AutoUpdateEntities;

                if (AutoUpdateEntities != null && AutoUpdateEntities.Exists(e => !string.IsNullOrEmpty(e.appname) && e.appname.Contains("com.improvative.techservice")))
                    return AutoUpdateEntities.FirstOrDefault(e => !string.IsNullOrEmpty(e.appname) && e.appname.Contains("com.improvative.techservice")).version;

                return "";
            }
        }
        



        [AresResourceDisplayName("DeviceModel.Fields.Platform_type")]
        public EnumDevicePlatform_type Platform_type { get; set; }
        
        public virtual string EnumPlatform_type_Text
		{
			get 
            { 
                return EnumExtensions.ToLocalizedtring(Platform_type);
            }
		}
        
        
        [AresResourceDisplayName("DeviceModel.Fields.Os_version")]
        public string Os_version { get; set; }
        
        
        
        [AresResourceDisplayName("DeviceModel.Fields.Current_carrier_network")]
        public string Current_carrier_network { get; set; }
        
        
        
        [AresResourceDisplayName("DeviceModel.Fields.Last_contact_time")]
        public DateTime? Last_contact_time { get; set; }
        
        
        
        [AresResourceDisplayName("DeviceModel.Fields.Battery_level")]
        public string Battery_level { get; set; }
        
        
        
        [AresResourceDisplayName("DeviceModel.Fields.Scan_status")]
        public EnumDeviceScan_status? Scan_status { get; set; }
        
        public virtual string EnumScan_status_Text
		{
			get 
            { 
                return EnumExtensions.ToLocalizedtring(Scan_status);
            }
		}
        
        
        [AresResourceDisplayName("DeviceModel.Fields.Agent_type")]
        public EnumDeviceAgent_type? Agent_type { get; set; }
        
        public virtual string EnumAgent_type_Text
		{
			get 
            { 
                return EnumExtensions.ToLocalizedtring(Agent_type);
            }
		}
        
        
        [AresResourceDisplayName("DeviceModel.Fields.Username")]
        public string Username { get; set; }
        
        
        
        [AresResourceDisplayName("DeviceModel.Fields.Mobile_number")]
        public string Mobile_number { get; set; }
        
        
        
        [AresResourceDisplayName("DeviceModel.Fields.Image_path")]
        public string Image_path { get; set; }
        
        
        
            [AresResourceDisplayName("DeviceModel.Fields.Filter_FormAnswerModel")]
            public AssetHealth.Models.Form_answer.FormAnswerModel Filter_FormAnswerModel { get; set; }   
                       
            [AresResourceDisplayName("DeviceModel.Fields.Filter_FormAnswerRoundModel")]
            public AssetHealth.Models.Form_answer_round.FormAnswerRoundModel Filter_FormAnswerRoundModel { get; set; }   
                       
            [AresResourceDisplayName("DeviceModel.Fields.Filter_SynchronizationModel")]
            public AssetHealth.Models.Synchronization.SynchronizationModel Filter_SynchronizationModel { get; set; }   
                       
            [AresResourceDisplayName("DeviceModel.Fields.Filter_SynchronizationDeviceModel")]
            public AssetHealth.Models.Synchronization_device.SynchronizationDeviceModel Filter_SynchronizationDeviceModel { get; set; }   
                       
            [AresResourceDisplayName("DeviceModel.Fields.Filter_SynchronizationLogModel")]
            public AssetHealth.Models.Synchronization_log.SynchronizationLogModel Filter_SynchronizationLogModel { get; set; }


        [AresResourceDisplayName("DeviceModel.Fields.UserList")]
        public string[] UserList { get; set; }
        public SelectList Users_SelectList { get; set; }


    }


}

AssetHealth/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Threading.Tasks;
using System.Web;
using System.IO;
using System.Web.Http;
using System.Net;
using System.Web.Http.ModelBinding;
using System.Web.Security;
using Ext.Net.MVC;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.OAuth;
using System.Web.Mvc;
using System.Linq;
using Ares.UMS.Svc.Directory;
using Ares.UMS.DTO.Users;
using Ares.UMS.Svc.Users;
using Ares.Web.Svc.Authentication;
using Ares.Web.Svc.Web;
using Ares.UMS.Svc.Common;
using Ares.UMS.DTO.Messages;
using Ares.UMS.Svc.Messages;
using Ares.Core.Helpers;
using Ares.UMS.DTO.Localization;
using Ares.UMS.Svc.Localization;
using Ares.UMS.DTO.Media;
using Ares.UMS.Svc.Media;
using Ares.Web.Models.Role;
using Ares.UMS.Svc.Security;
using Ares.UMS.DTO.Security;
using Ares.Web.Helpers;
using Ares.Web.Attributes;
using Ares.Web.Controllers;
using Ares.UMS.Svc.Configuration;
using Ares.UMS.DTO.Configuration;
using Ares.UMS.Svc;
using Ares.Web.Razor.Extensions.Datatable.Model;
using AssetHealth.Extensions;
using AssetHealth.Models.User;
using AssetHealth.Common.Svc;
using AssetHealth.Common.DTO;
using AssetHealth.Models.Configuration;
using AssetHealth.Models.Device;
using AssetHealth.Models.User;
using AssetHealth.Models.Form_answer;
using AssetHealth.Models.Form_question;
using AssetHealth.Models.Form_answer_round;
using AssetHealth.Models.Synchronization_detail;
using AssetHealth.Models.Synchronization;
using AssetHealth.Models.Synchronization_log;
using Ares.Sync.Svc;
using Ares.Sync.DTO;
using System.Collections.ObjectModel;
using Ares.DTO;
using Ares.Svc;
using AssetHealth.Common.DTO.Extensions;
using System.Web.Routing;
using AssetHealth.Common.DAL;
using AssetHealth.Models.Synchronization_device;
using Newtonsoft.Json;
using Ares.Sync.Controllers;
using Ares.Web.JSON;
using AssetHealth.Mapper;

namespace AssetHealth.Contollers
{
	
    public partial class DeviceController : BaseAresController
	{
		#region Fields

        private readonly IDeviceSvc _iDevicesvc;
        
        private readonly IUserSvc _iUsersvc;
        private readonly IFormAnswerSvc _iFormAnswersvc;
        private readonly IFormQuestionSvc _iFormQuestionsvc;
        private readonly IFormAnswerRoundSvc _iFormAnswerRoundsvc;
        private readonly IParameterItemSvc _iParameterItemsvc;
        private readonly ISynchronizationDetailSvc _iSynchronizationDetailsvc;
        private readonly ISynchronizationDeviceSvc _iSynchronizationDevicesvc;
        private readonly ISynchronizationSvc _iSynchronizationsvc;
        private readonly ISynchronizationLogSvc _iSynchronizationLogsvc;
        
        private readonly IStateProvinceSvc _stateProvinceSvc;
        private readonly ISettingSvc _settingSvc;
        private readonly FileSettings _fileSettings;
        
        private readonly IGenericAttributeSvc _genericAttributeSvc;
        private readonly ILocalizationSvc _localizationSvc;
        private readonly IPictureSvc _pictureSvc;
        private readonly IUserSvc _userSvc;
        private readonly IRoleSvc _roleSvc;
        private readonly IPermissionSvc _permissionSvc;
        private readonly IMenuSvc _menuSvc;
        private readonly IWorkContext _workContext;
        private readonly IUserRegistrationSvc _userRegistrationSvc;
        private readonly IAuthenticationSvc _authenticationSvc;
        private readonly IWorkflowMessageSvc _workflowMessageSvc;
        private readonly INewsLetterSubscriptionSvc _newsLetterSubscriptionSvc;
        private readonly IWebHelper _webHelper;
        private readonly UserSettings _userSettings;
        private readonly LocalizationSettings _localizationSettings;
        private readonly MediaSettings _mediaSettings;

	    #endregion

		#region Constructors

        public DeviceController(IDeviceSvc Devicesvc,
        IUserSvc Usersvc,
        IFormAnswerSvc FormAnswersvc,
        IFormQuestionSvc FormQuestionsvc,
        IFormAnswerRoundSvc FormAnswerRoundsvc,
        IParameterItemSvc ParameterItemsvc,
        ISynchronizationDetailSvc SynchronizationDetailsvc,
        ISynchronizationDeviceSvc SynchronizationDevicesvc,
        ISynchronizationSvc Synchronizationsvc,
        ISynchronizationLogSvc SynchronizationLogsvc,
            IStateProvinceSvc stateProvinceSvc, IGenericAttributeSvc genericAttributeSvc, ILocalizationSvc localizationSvc,  
            UserSettings userSettings, IPictureSvc pictureSvc, ISettingSvc settingSvc, FileSettings fileSettings,
            IUserSvc userSvc, IRoleSvc roleSvc, IPermissionSvc permissionSvc, IMenuSvc menuSvc, IWorkContext workContext, IUserRegistrationSvc userRegistrationSvc, IAuthenticationSvc authenticationSvc, IWorkflowMessageSvc workflowMessageSvc,
            INewsLetterSubscriptionSvc newsLetterSubscriptionSvc, IWebHelper webHelper, LocalizationSettings localizationSettings, MediaSettings mediaSettings)
		{
            this._iDevicesvc = Devicesvc;
            
            this._iUsersvc = Usersvc;
            this._iFormAnswersvc = FormAnswersvc;
            this._iFormQuestionsvc = FormQuestionsvc;
            this._iFormAnswerRoundsvc = FormAnswerRoundsvc;
            this._iParameterItemsvc = ParameterItemsvc;
            this._iSynchronizationDetailsvc = SynchronizationDetailsvc;
            this._iSynchronizationDevicesvc = SynchronizationDevicesvc;
            this._iSynchronizationsvc = Synchronizationsvc;
            this._iSynchronizationLogsvc = SynchronizationLogsvc;
            this._settingSvc = settingSvc;
            this._fileSettings = fileSettings;
            
            this._stateProvinceSvc = stateProvinceSvc;
            this._genericAttributeSvc = genericAttributeSvc;
            this._pictureSvc = pictureSvc;
            this._localizationSvc = localizationSvc;
            this._userSettings = userSettings;
            this._userSvc = userSvc;
            this._roleSvc = roleSvc;
            this._permissionSvc = permissionSvc;
            this._menuSvc = menuSvc;
            this._workContext = workContext;
            this._userRegistrationSvc = userRegistrationSvc;
            this._authenticationSvc = authenticationSvc;
            this._workflowMessageSvc = workflowMessageSvc;
            this._newsLetterSubscriptionSvc = newsLetterSubscriptionSvc;
            this._webHelper = webHelper;
            this._localizationSettings = localizationSettings;
            this._mediaSettings = mediaSettings;
		}

		#endregion 

        #region Utilities
        
        
        #endregion

        #region Device methods

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        [AresAuthorize(ResourceKey = "Admin.Device.Read")]
        public ActionResult List()
        {
            DeviceModel model = new DeviceModel();
            //model. = _roleSvc.GetAll().ToList().Select(x => x.ToModel()).ToList();
            FillDropDowns(model);
            
            
            //FillDropDownFormAnswer(model.Filter_FormAnswerModel);
                       
            
            //FillDropDownFormAnswerRound(model.Filter_FormAnswerRoundModel);
                       
            
            //FillDropDownSynchronization(model.Filter_SynchronizationModel);
                       
            
            //FillDropDownSynchronizationDevice(model.Filter_SynchronizationDeviceModel);
                       
            
            //FillDropDownSynchronizationLog(model.Filter_SynchronizationLogModel);
                       
            
            return View(model);
        }

        [AresAuthorize(ResourceKey = "Admin.Device.Read")]
        public ActionResult ListDeviceDatatable(Ares.Web.Razor.Extensions.Datatable.Model.DTParameterModel model)
        {
            var models = _iDevicesvc.GetAll();

            /*
            if (!_workContext.CurrentUser.IsAdmin())
            {
                int userId = _workContext.CurrentUser.Id;
                models = models.Where(d => d.User_From_DeviceUserMapping.Any(dum => dum.Id == userId));
            }
              */  

            if (model.Search != null && !string.IsNullOrEmpty(model.Search.Value))
            {
                models = models.Where(m => m.Device_name.Contains(model.Search.Value));
            }
            
            if(model.IsSearchValueExist("EnumDevice_type_Text"))
            {
                int tmpValue = int.Parse(model.GetSearchValue("EnumDevice_type_Text"));
                models = models.Where(m => m.Device_type.HasValue && (int)m.Device_type == tmpValue);
            }
            if(model.IsSearchValueExist("Udid"))
            {
                string tmpValue = model.GetSearchValue("Udid");
                models = models.Where(m => m.Udid.Contains(tmpValue));
            }
            if(model.IsSearchValueExist("Device_name"))
            {
                string tmpValue = model.GetSearchValue("Device_name");
                models = models.Where(m => m.Device_name.Contains(tmpValue));
            }
            if(model.IsSearchValueExist("Device_model"))
            {
                string tmpValue = model.GetSearchValue("Device_model");
                models = models.Where(m => m.Device_model.Contains(tmpValue));
            }
            if(model.IsSearchValueExist("Platform_type_Text"))
            {
                
            }
            if(model.IsSearchValueExist("Os_version"))
            {
                string tmpValue = model.GetSearchValue("Os_version");
                models = models.Where(m => m.Os_version.Contains(tmpValue));
            }
            if(model.IsSearchValueExist("Current_carrier_network"))
            {

AssetHealth/Views/Device/Create.cshtml
@using AssetHealth.Models.Device;
@model DeviceModel
@{
    Layout = Request.IsAjaxRequest() ? "" : "~/Views/Shared/_ColumnsThree.cshtml";
    //page title
    ViewBag.Title = T("Admin.Device.AddNew").Text;
}

@using (Html.BeginForm("Create", "Device", FormMethod.Post))
{
    <div class="row">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-customers.png")" alt="" />
            @T("Admin.Device.AddDeviceDetails") -
            @Html.ActionLink("(" + T("Admin.Common.BackToList") + ")", "List")
        </div>
        <div class="pull-right" style="margin-right:25px;">
            <button type="submit" name="save" class="btn green">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>

            
        </div>
    </div>
    <br />
    @Html.Partial("CreateOrUpdate", Model)
}

 @section jQueryOnReadyScripts {
     $("#UserList").select2({multiple: true });
}

@section beforeFooter{

    <script type="text/javascript" src="~/Scripts/pages/Device-input-mask.js"></script>
}

AssetHealth/Views/Device/CreateFormAnswer.cshtml
@using AssetHealth.Models.Form_answer;
@model FormAnswerModel
@{
    Layout = Request.IsAjaxRequest() ? "" : "~/Views/Shared/_ColumnsThree.cshtml";
    //page title
    ViewBag.Title = T("Admin.FormAnswer.AddNew").Text;
}

@using (Html.BeginForm("CreateFormAnswer", "Device", FormMethod.Post))
{
    <div class="row">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-customers.png")" alt="" />
            @T("Admin.FormAnswer.AddFormAnswerDetails") -
            @Html.ActionLink("(" + T("Admin.Common.BackToList") + ")", "Edit/" + Request.QueryString["DeviceModelId"])
        </div>
        <div class="pull-right" style="margin-right:25px;">
            <button type="submit" name="save" class="btn green">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>

            
        </div>
    </div>
    <br />
    @Html.Partial("CreateOrUpdateFormAnswer", Model)
}

 @section jQueryOnReadyScripts {
}

@section beforeFooter{

    <script type="text/javascript" src="~/Scripts/pages/FormAnswer-input-mask.js"></script>
}

AssetHealth/Views/Device/CreateFormAnswerRound.cshtml
@using AssetHealth.Models.Form_answer_round;
@model FormAnswerRoundModel
@{
    Layout = Request.IsAjaxRequest() ? "" : "~/Views/Shared/_ColumnsThree.cshtml";
    //page title
    ViewBag.Title = T("Admin.FormAnswerRound.AddNew").Text;
}

@using (Html.BeginForm("CreateFormAnswerRound", "Device", FormMethod.Post))
{
    <div class="row">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-customers.png")" alt="" />
            @T("Admin.FormAnswerRound.AddFormAnswerRoundDetails") -
            @Html.ActionLink("(" + T("Admin.Common.BackToList") + ")", "Edit/" + Request.QueryString["DeviceModelId"])
        </div>
        <div class="pull-right" style="margin-right:25px;">
            <button type="submit" name="save" class="btn green">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>

            
        </div>
    </div>
    <br />
    @Html.Partial("CreateOrUpdateFormAnswerRound", Model)
}

 @section jQueryOnReadyScripts {
}

@section beforeFooter{

    <script type="text/javascript" src="~/Scripts/pages/FormAnswerRound-input-mask.js"></script>
}

AssetHealth/Views/Device/CreateSynchronization.cshtml
@using AssetHealth.Models.Synchronization;
@model SynchronizationModel
@{
    Layout = Request.IsAjaxRequest() ? "" : "~/Views/Shared/_ColumnsThree.cshtml";
    //page title
    ViewBag.Title = T("Admin.Synchronization.AddNew").Text;
}

@using (Html.BeginForm("CreateSynchronization", "Device", FormMethod.Post))
{
    <div class="row">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-customers.png")" alt="" />
            @T("Admin.Synchronization.AddSynchronizationDetails") -
            @Html.ActionLink("(" + T("Admin.Common.BackToList") + ")", "Edit/" + Request.QueryString["DeviceModelId"])
        </div>
        <div class="pull-right" style="margin-right:25px;">
            <button type="submit" name="save" class="btn green">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>

            
        </div>
    </div>
    <br />
    @Html.Partial("CreateOrUpdateSynchronization", Model)
}

 @section jQueryOnReadyScripts {
}

@section beforeFooter{

    <script type="text/javascript" src="~/Scripts/pages/Synchronization-input-mask.js"></script>
}

AssetHealth/Views/Device/EditFormAnswerRound.cshtml
@using AssetHealth.Models.Form_answer_round;
@model FormAnswerRoundModel

@{
    Layout = Request.IsAjaxRequest() ? "" : "~/Views/Shared/_ColumnsThree.cshtml";
    //page title
    ViewBag.Title = T("Admin.FormAnswerRound.EditFormAnswerRoundDetails").Text;
}
@using (Html.BeginForm("EditFormAnswerRound", "Device", FormMethod.Post))
{
    <div class="row">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-customers.png")" alt="" />
            @T("Admin.FormAnswerRound.EditFormAnswerRoundDetails") - @Model.Object_id
            @Html.ActionLink("(" + T("Admin.Common.BackToList") + ")", "Edit/" + Request.QueryString["DeviceModelId"])
        </div>
        <div class="pull-right" style="margin-right:25px;">
            <button type="submit" name="save" class="btn green">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            &nbsp;
            <a class="btn red" data-toggle="modal" data-id="@Model.Id" data-id="@Model.Id" data-deleteurl="@Url.Action("DeleteFormAnswerRound", new {Id = Model.Id})" href="#modalDeleteConfirm">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </a>
            
        </div>
    </div>
    <br />
    @Html.Partial("CreateOrUpdateFormAnswerRound", Model)
}

 
 @section jQueryOnReadyScripts {
 



    
    @(Url.Datatables().CreateDatatable("#dataTableFormAnswer", "ListFormAnswerDatatable", "FormAnswerRound", null, true, new { FormAnswerRoundModelId = Model.Id }, "dataTableFormAnswer").AddColumn("Id")
                                        .AddColumn("Form_question_id_Text")
                                        .AddColumn("Device_id_Text")
                                        .AddColumn("Previous_answer_Text")
                                        .AddColumn("Username")
                                        .AddColumn("Read_no")
                                        .AddColumn("Warning_type_Text")
                                        .AddColumn("Answer")
                                        .AddColumn("Long_answer")
                                        .AddColumn("Converted_answer")
                                        .AddColumn("Json")
                                        .AddCustomJavascriptColumn("", "return formatJSONDate(full.Required_read_datetime)")
                                        
                                        .AddCustomJavascriptColumn("", "return formatJSONDate(full.Actual_read_datetime)")
                                        
                                        .AddColumn("Description")
                                        .AddColumn("Notes")
                                        .AddColumn("Udid")
    .AddCustomJavascriptColumn("", "return getDatatableEditDeleteButtonString('" + @Url.Action("EditFormAnswer", "Device") + "/' + full.Id , full.Id, true,  true, 'FormAnswer') ;")
    .SetLanguageUrl(WorkContext.WorkingLanguage.Id == 1 ? "~/Content/assets/global/plugins/datatables/turkish.json" : null)
    .SetLenghtMenu("5,10,50,100")
    .AddAttribute("'deferLoading' : 0")
    .AddAttribute("'responsive' : false ") @* DataTableResponsiveAttribute *@
    .AddAttribute("'scrollX' : true ")
    .AddAttribute("'buttons' :  DataTablePrintButtonAttribute  ")
    .Initialize());
    
    window.dataTableFormAnswerOptions = dataTableFormAnswerOptions;

                 $('#btnFilterFormAnswer').click(function () {
                        dataTableFormAnswer.column('Form_question_id:name').search($('#Form_question_id').val().trim());
                        dataTableFormAnswer.column('Device_id:name').search($('#Device_id').val().trim());
                        dataTableFormAnswer.column('Previous_answer:name').search($('#Previous_answer').val().trim());
                        dataTableFormAnswer.column('Username:name').search($('#Username').val().trim());
                        dataTableFormAnswer.column('Read_no:name').search($('#Read_no').val().trim());
                        dataTableFormAnswer.column('Warning_type:name').search($('#Warning_type').val().trim());
                        dataTableFormAnswer.column('Answer:name').search($('#Answer').val().trim());
                        dataTableFormAnswer.column('Converted_answer:name').search($('#Converted_answer').val().trim());


                        dataTableFormAnswer.column('Description:name').search($('#Description').val().trim());
                        dataTableFormAnswer.column('Udid:name').search($('#Udid').val().trim());
                    //Apply search for Employee Name // DataTable column index 0
                   // dataTable.columns(0).search($('#txtEmployeeName').val().trim());
                    //Apply search for Country // DataTable column index 3
                    //dataTable.columns(0).search($('#ddCountry').val().trim());

                    //hit search on server
                dataTableFormAnswer.draw();
            });
            
            
                $('#btnResetFormAnswer').click(function () {

                    resetDatatableSearch('dataTableFormAnswer');

                });


        
             
        
 
       setTimeout(function(){
        $('a[href="#tab_FormAnswerRound_@Model.SelectedTab"]').tab('show');
        }, 500);
 
}

@section beforeFooter{

    <script type="text/javascript" src="~/Scripts/pages/FormAnswerRound-input-mask.js"></script>
}