AssetHealth/Models/EqChannel/EqChannelModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Ares.UMS.DTO.Security;
using Ares.UMS.DTO.Users;
using Ares.Web.Models;
using Ares.Web.Razor;
using System.Web.Mvc;
using FluentValidation.Attributes;
using AssetHealth.Validators;
using AssetHealth.Models.Equipment;
using AssetHealth.Common.DTO.Enums;
using Ares.Web.Extensions;
using Ares.Web.Models.Parameter_item;

namespace AssetHealth.Models.Eq_channel
{
    [Validator(typeof(EqChannelModelValidator))]
    public partial class EqChannelModel : BaseAresModel //, ILocalizedModel<TopicLocalizedModel>
    {
        public EqChannelModel()
        {
            //Locales = new List<TopicLocalizedModel>();
            SelectedTab = "1";
            
            Filter_EqThresholdModel = new AssetHealth.Models.Eq_threshold.EqThresholdModel();  
                       
            
            Filter_EqWarningModel = new AssetHealth.Models.Eq_warning.EqWarningModel();  
                       
        }
        
        public string SelectedTab { get; set; }

        
        [AresResourceDisplayName("EqChannelModel.Fields.Id")]
        public int Id { get; set; }
        

        
        [AresResourceDisplayName("EqChannelModel.Fields.Object_id")]
        public string Object_id { get; set; }
        
        
        
        [AresResourceDisplayName("EqChannelModel.Fields.Equipment_id")]
        public int Equipment_id { get; set; }
        
        
        
        [AresResourceDisplayName("EqChannelModel.Fields.Sensor_type")]
        public int? Sensor_type { get; set; }
        
        
        
        [AresResourceDisplayName("EqChannelModel.Fields.Name")]
        public string Name { get; set; }
        
        
        
        [AresResourceDisplayName("EqChannelModel.Fields.Channel_number")]
        public int? Channel_number { get; set; }
        
        
        
        [AresResourceDisplayName("EqChannelModel.Fields.Active")]
        public bool Active { get; set; }
        
        
        
        [AresResourceDisplayName("EqChannelModel.Fields.Cid")]
        public string Cid { get; set; }
        
        
        
        [AresResourceDisplayName("EqChannelModel.Fields.Description")]
        public string Description { get; set; }
        
        
        
            public ParameterItemModel CHANNEL_SENSOR_TYPE_PARAMITEMS { get; set; }  
            
            [AresResourceDisplayName("EqChannelModel.Fields.Sensor_type_Text")]
            public string Sensor_type_Text { get; set; }   
            public SelectList Sensor_type_ParameterItem_SelectList { get; set; }           
            
            public EquipmentModel channel_equipment { get; set; }  
            
            [AresResourceDisplayName("EqChannelModel.Fields.Equipment_id_Text")]
            public string Equipment_id_Text { get; set; }   
            public SelectList Equipment_id_Equipment_SelectList { get; set; }           
            
            [AresResourceDisplayName("EqChannelModel.Fields.Filter_EqThresholdModel")]
            public AssetHealth.Models.Eq_threshold.EqThresholdModel Filter_EqThresholdModel { get; set; }   
                       
            [AresResourceDisplayName("EqChannelModel.Fields.Filter_EqWarningModel")]
            public AssetHealth.Models.Eq_warning.EqWarningModel Filter_EqWarningModel { get; set; }

        [AresResourceDisplayName("EqChannelModel.Fields.QuestionList")]
        public string[] QuestionList { get; set; }
        public SelectList Questions_SelectList { get; set; }

        [AresResourceDisplayName("EqChannelModel.Fields.Filter_EqLocation")]
        public string Filter_EqLocation_Text { get; set; }
        public SelectList Filter_EqLocation_SelectList { get; set; }
    }


}

AssetHealth/Controllers/EqChannelController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Threading.Tasks;
using System.Web;
using System.IO;
using System.Web.Http;
using System.Net;
using System.Web.Http.ModelBinding;
using System.Web.Security;
using Ext.Net.MVC;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.OAuth;
using System.Web.Mvc;
using System.Linq;
using Ares.UMS.Svc.Directory;
using Ares.UMS.DTO.Users;
using Ares.UMS.Svc.Users;
using Ares.Web.Svc.Authentication;
using Ares.Web.Svc.Web;
using Ares.UMS.Svc.Common;
using Ares.UMS.DTO.Messages;
using Ares.UMS.Svc.Messages;
using Ares.Core.Helpers;
using Ares.UMS.DTO.Localization;
using Ares.UMS.Svc.Localization;
using Ares.UMS.DTO.Media;
using Ares.UMS.Svc.Media;
using Ares.Web.Models.Role;
using Ares.UMS.Svc.Security;
using Ares.UMS.DTO.Security;
using Ares.Web.Helpers;
using Ares.Web.Attributes;
using Ares.Web.Controllers;
using Ares.UMS.Svc.Configuration;
using Ares.UMS.DTO.Configuration;
using Ares.UMS.Svc;
using Ares.Web.Razor.Extensions.Datatable.Model;
using AssetHealth.Extensions;
using AssetHealth.Models.User;
using AssetHealth.Common.Svc;
using AssetHealth.Common.DTO;
using AssetHealth.Models.Configuration;
using AssetHealth.Models.Eq_channel;
using AssetHealth.Models.User;
using AssetHealth.Models.Form_answer;
using AssetHealth.Models.Form_question;
using AssetHealth.Models.Form_answer_round;
using AssetHealth.Models.Synchronization_detail;
using AssetHealth.Models.Synchronization_device;
using AssetHealth.Models.Synchronization;
using AssetHealth.Models.Synchronization_log;
using AssetHealth.Models.Equipment;
using AssetHealth.Models.Eq_threshold;
using AssetHealth.Models.Eq_warning;
using Ares.Sync.Svc;
using AssetHealth.Common.DTO.Extensions;
using AssetHealth.Mapper;
using AssetHealth.Common.DTO.Enums;

namespace AssetHealth.Contollers
{
	
    public partial class EqChannelController : BaseAresController
	{
		#region Fields

        private readonly IEqChannelSvc _iEqChannelsvc;
        
        private readonly IUserSvc _iUsersvc;
        private readonly IFormAnswerSvc _iFormAnswersvc;
        private readonly IFormQuestionSvc _iFormQuestionsvc;
        private readonly IFormAnswerRoundSvc _iFormAnswerRoundsvc;
        private readonly IParameterItemSvc _iParameterItemsvc;
        private readonly ISynchronizationDetailSvc _iSynchronizationDetailsvc;
        private readonly ISynchronizationDeviceSvc _iSynchronizationDevicesvc;
        private readonly ISynchronizationSvc _iSynchronizationsvc;
        private readonly ISynchronizationLogSvc _iSynchronizationLogsvc;
        private readonly IEquipmentSvc _iEquipmentsvc;
        private readonly IEqThresholdSvc _iEqThresholdsvc;
        private readonly IEqWarningSvc _iEqWarningsvc;
        private readonly IEqLocationSvc _iEqLocationSvc;

        private readonly IStateProvinceSvc _stateProvinceSvc;
        private readonly ISettingSvc _settingSvc;
        private readonly FileSettings _fileSettings;
        
        private readonly IGenericAttributeSvc _genericAttributeSvc;
        private readonly ILocalizedPropertySvc _iLocalizedPropertySvc;
        private readonly ILocalizationSvc _localizationSvc;
        private readonly IPictureSvc _pictureSvc;
        private readonly IUserSvc _userSvc;
        private readonly IRoleSvc _roleSvc;
        private readonly IPermissionSvc _permissionSvc;
        private readonly IMenuSvc _menuSvc;
        private readonly IWorkContext _workContext;
        private readonly IUserRegistrationSvc _userRegistrationSvc;
        private readonly IAuthenticationSvc _authenticationSvc;
        private readonly IWorkflowMessageSvc _workflowMessageSvc;
        private readonly INewsLetterSubscriptionSvc _newsLetterSubscriptionSvc;
        private readonly IWebHelper _webHelper;
        private readonly UserSettings _userSettings;
        private readonly LocalizationSettings _localizationSettings;
        private readonly MediaSettings _mediaSettings;

	    #endregion

		#region Constructors

        public EqChannelController(IEqChannelSvc EqChannelsvc,
        IUserSvc Usersvc,
        IFormAnswerSvc FormAnswersvc,
        IFormQuestionSvc FormQuestionsvc,
        IFormAnswerRoundSvc FormAnswerRoundsvc,
        IParameterItemSvc ParameterItemsvc,
        ISynchronizationDetailSvc SynchronizationDetailsvc,
        ISynchronizationDeviceSvc SynchronizationDevicesvc,
        ISynchronizationSvc Synchronizationsvc,
        ISynchronizationLogSvc SynchronizationLogsvc,
        IEquipmentSvc Equipmentsvc,
        IEqThresholdSvc EqThresholdsvc,
        IEqWarningSvc EqWarningsvc,
            IStateProvinceSvc stateProvinceSvc, IGenericAttributeSvc genericAttributeSvc, ILocalizationSvc localizationSvc, ILocalizedPropertySvc iLocalizedPropertySvc,
            UserSettings userSettings, IPictureSvc pictureSvc, ISettingSvc settingSvc, FileSettings fileSettings, IEqLocationSvc iEqLocationSvc,
            IUserSvc userSvc, IRoleSvc roleSvc, IPermissionSvc permissionSvc, IMenuSvc menuSvc, IWorkContext workContext, IUserRegistrationSvc userRegistrationSvc, IAuthenticationSvc authenticationSvc, IWorkflowMessageSvc workflowMessageSvc,
            INewsLetterSubscriptionSvc newsLetterSubscriptionSvc, IWebHelper webHelper, LocalizationSettings localizationSettings, MediaSettings mediaSettings)
		{
            this._iEqChannelsvc = EqChannelsvc;
            
            this._iUsersvc = Usersvc;
            this._iFormAnswersvc = FormAnswersvc;
            this._iFormQuestionsvc = FormQuestionsvc;
            this._iFormAnswerRoundsvc = FormAnswerRoundsvc;
            this._iParameterItemsvc = ParameterItemsvc;
            this._iSynchronizationDetailsvc = SynchronizationDetailsvc;
            this._iSynchronizationDevicesvc = SynchronizationDevicesvc;
            this._iSynchronizationsvc = Synchronizationsvc;
            this._iSynchronizationLogsvc = SynchronizationLogsvc;
            this._iEquipmentsvc = Equipmentsvc;
            this._iEqThresholdsvc = EqThresholdsvc;
            this._iEqWarningsvc = EqWarningsvc;
            this._settingSvc = settingSvc;
            this._fileSettings = fileSettings;

            this._iEqLocationSvc = iEqLocationSvc;
            this._iLocalizedPropertySvc = iLocalizedPropertySvc;
            this._stateProvinceSvc = stateProvinceSvc;
            this._genericAttributeSvc = genericAttributeSvc;
            this._pictureSvc = pictureSvc;
            this._localizationSvc = localizationSvc;
            this._userSettings = userSettings;
            this._userSvc = userSvc;
            this._roleSvc = roleSvc;
            this._permissionSvc = permissionSvc;
            this._menuSvc = menuSvc;
            this._workContext = workContext;
            this._userRegistrationSvc = userRegistrationSvc;
            this._authenticationSvc = authenticationSvc;
            this._workflowMessageSvc = workflowMessageSvc;
            this._newsLetterSubscriptionSvc = newsLetterSubscriptionSvc;
            this._webHelper = webHelper;
            this._localizationSettings = localizationSettings;
            this._mediaSettings = mediaSettings;
		}

		#endregion 

        #region Utilities
        
        
        #endregion

        #region EqChannel methods

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        [AresAuthorize(ResourceKey = "Admin.EqChannel.Read")]
        public ActionResult List()
        {
            EqChannelModel model = new EqChannelModel();
            //model. = _roleSvc.GetAll().ToList().Select(x => x.ToModel()).ToList();
            FillDropDowns(model);
            
            
            FillDropDownEqThreshold(model.Filter_EqThresholdModel);
                       
            
            FillDropDownEqWarning(model.Filter_EqWarningModel);

            model.Active = true;
                       
            
            return View(model);
        }

        [AresAuthorize(ResourceKey = "Admin.EqChannel.Read")]
        public ActionResult ListEqChannelDatatable(Ares.Web.Razor.Extensions.Datatable.Model.DTParameterModel model)
        {
            var models = _iEqChannelsvc.GetAll();

            if (!_workContext.CurrentUser.IsAdmin())
            {
                List<int> relatedLocationIds = _workContext.CurrentUser.RelatedLocations().Select(r => r.Id).ToList();
                models = models.Where(e => relatedLocationIds.Contains(e.channel_equipment.Location.Id));
            }

            if (model.Search != null && !string.IsNullOrEmpty(model.Search.Value))
            {
                models = models.Where(m => m.Object_id.Contains(model.Search.Value));
            }
            if (model.IsSearchValueExist("Filter_EqLocation_Text"))
            {
                int tmpValue = int.Parse(model.GetSearchValue("Filter_EqLocation_Text"));
                models = models.Where(m => m.channel_equipment.Eq_location_id == tmpValue);
            }
            

            if (model.IsSearchValueExist("Name"))
            {
                string tmpValue = model.GetSearchValue("Name");
                models = models.Where(m => m.Name.Contains(tmpValue));
            }

            if (model.IsSearchValueExist("Equipment_id_Text"))
            {
                int tmpValue = int.Parse(model.GetSearchValue("Equipment_id_Text"));
                models = models.Where(m => m.Equipment_id == tmpValue);
            }
            if(model.IsSearchValueExist("Sensor_type_Text"))
            {
                int tmpValue = int.Parse(model.GetSearchValue("Sensor_type_Text"));
                models = models.Where(m => m.Sensor_type == tmpValue);
            }
            if(model.IsSearchValueExist("Channel_number"))

AssetHealth/Views/EqChannel/Create.cshtml
@using AssetHealth.Models.Eq_channel;
@model EqChannelModel
@{
    Layout = Request.IsAjaxRequest() ? "" : "~/Views/Shared/_ColumnsThree.cshtml";
    //page title
    ViewBag.Title = T("Admin.EqChannel.AddNew").Text;
}

@using (Html.BeginForm("Create", "EqChannel", FormMethod.Post))
{
    <div class="row">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-customers.png")" alt="" />
            @T("Admin.EqChannel.AddEqChannelDetails") -
            @Html.ActionLink("(" + T("Admin.Common.BackToList") + ")", "List")
        </div>
        <div class="pull-right" style="margin-right:25px;">
            <button type="submit" name="save" class="btn green">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>

            
        </div>
    </div>
    <br />
    @Html.Partial("CreateOrUpdate", Model)
}

 @section jQueryOnReadyScripts {
     $("#QuestionList").select2({multiple: true });
}

@section beforeFooter{

    <script type="text/javascript" src="~/Scripts/pages/EqChannel-input-mask.js"></script>
}

AssetHealth/Views/EqChannel/CreateEqThreshold.cshtml
@using AssetHealth.Models.Eq_threshold;
@model EqThresholdModel
@{
    Layout = Request.IsAjaxRequest() ? "" : "~/Views/Shared/_ColumnsThree.cshtml";
    //page title
    ViewBag.Title = T("Admin.EqThreshold.AddNew").Text;
}

@using (Html.BeginForm("CreateEqThreshold", "EqChannel", FormMethod.Post))
{
    <div class="row">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-customers.png")" alt="" />
            @T("Admin.EqThreshold.AddEqThresholdDetails") -
            @Html.ActionLink("(" + T("Admin.Common.BackToList") + ")", "Edit/" + Request.QueryString["EqChannelModelId"])
        </div>
        <div class="pull-right" style="margin-right:25px;">
            <button type="submit" name="save" class="btn green">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>

            
        </div>
    </div>
    <br />
    @Html.Partial("CreateOrUpdateEqThreshold", Model)
}

 @section jQueryOnReadyScripts {
}

@section beforeFooter{

    <script type="text/javascript" src="~/Scripts/pages/EqThreshold-input-mask.js"></script>
}

AssetHealth/Views/EqChannel/CreateEqWarning.cshtml
@using AssetHealth.Models.Eq_warning;
@model EqWarningModel
@{
    Layout = Request.IsAjaxRequest() ? "" : "~/Views/Shared/_ColumnsThree.cshtml";
    //page title
    ViewBag.Title = T("Admin.EqWarning.AddNew").Text;
}

@using (Html.BeginForm("CreateEqWarning", "EqChannel", FormMethod.Post))
{
    <div class="row">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-customers.png")" alt="" />
            @T("Admin.EqWarning.AddEqWarningDetails") -
            @Html.ActionLink("(" + T("Admin.Common.BackToList") + ")", "Edit/" + Request.QueryString["EqChannelModelId"])
        </div>
        <div class="pull-right" style="margin-right:25px;">
            <button type="submit" name="save" class="btn green">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>

            
        </div>
    </div>
    <br />
    @Html.Partial("CreateOrUpdateEqWarning", Model)
}

 @section jQueryOnReadyScripts {
}

@section beforeFooter{

    <script type="text/javascript" src="~/Scripts/pages/EqWarning-input-mask.js"></script>
}

AssetHealth/Views/EqChannel/Edit.cshtml
@using AssetHealth.Models.Eq_channel;
@model EqChannelModel

@{
    Layout = Request.IsAjaxRequest() ? "" : "~/Views/Shared/_ColumnsThree.cshtml";
    //page title
    ViewBag.Title = T("Admin.EqChannel.EditEqChannelDetails").Text;
}
@using (Html.BeginForm("Edit", "EqChannel", FormMethod.Post))
{
    <div class="row">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-customers.png")" alt="" />
            @T("Admin.EqChannel.EditEqChannelDetails") - @Model.Name
            @Html.ActionLink("(" + T("Admin.Common.BackToList") + ")", "List")
        </div>
        <div class="pull-right" style="margin-right:25px;">
            <button type="submit" name="save" class="btn green">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            &nbsp;
            <a class="btn red" data-toggle="modal" data-id="@Model.Id" data-id="@Model.Id" data-deleteurl="@Url.Action("Delete", new {Id = Model.Id})" href="#modalDeleteConfirm">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </a>
            
        </div>
    </div>
    <br />
    @Html.Partial("CreateOrUpdate", Model)
}

 
 @section jQueryOnReadyScripts {
 
    



    
    @(Url.Datatables().CreateDatatable("#dataTableEqThreshold", "ListEqThresholdDatatable", "EqChannel", null, true, new { EqChannelModelId = Model.Id }, "dataTableEqThreshold").AddColumn("Id")
                                        .AddColumn("Name")
                                        //.AddColumn("Description")
                                        .AddColumn("Lower_limit")
                                        .AddColumn("Upper_limit_Text")
                                        .AddColumn("Warning_type_Text")
                                        .AddCustomJavascriptColumn("Active", " return full.Active ? \"<i class='fa fa-check' style='font-size: 18pt;color:green' />\" : \"<i class='fa fa-times' style='font-size: 18pt;color:red' /> \" ")
    .AddCustomJavascriptColumn("", "return getDatatableEditDeleteButtonString('" + @Url.Action("EditEqThreshold", "EqChannel") + "/' + full.Id , full.Id, true,  true, 'EqThreshold') ;")
    .SetLanguageUrl(WorkContext.WorkingLanguage.Id == 1 ? "~/Content/assets/global/plugins/datatables/turkish.json" : null)
    .SetLenghtMenu("5,10,50,100")
    .AddAttribute("'deferLoading' : 0")
    .AddAttribute("'responsive' : false ") @* DataTableResponsiveAttribute *@
    .AddAttribute("'scrollX' : true ")
    .AddAttribute("'buttons' :  DataTablePrintButtonAttribute  ")
    .Initialize());
    
    window.dataTableEqThresholdOptions = dataTableEqThresholdOptions;

                 $('#btnFilterEqThreshold').click(function () {
                        dataTableEqThreshold.column('Name:name').search($('#Name').val().trim());
                        dataTableEqThreshold.column('Warning_type:name').search($('#Warning_type').val().trim());
                        dataTableEqThreshold.column('Active:name').search($('#Active').prop('checked'));
                    //Apply search for Employee Name // DataTable column index 0
                   // dataTable.columns(0).search($('#txtEmployeeName').val().trim());
                    //Apply search for Country // DataTable column index 3
                    //dataTable.columns(0).search($('#ddCountry').val().trim());

                    //hit search on server
                dataTableEqThreshold.draw();
            });
            
            
                $('#btnResetEqThreshold').click(function () {

                    resetDatatableSearch('dataTableEqThreshold');

                });


        
     
    



    
    @(Url.Datatables().CreateDatatable("#dataTableEqWarning", "ListEqWarningDatatable", "EqChannel", null, true, new { EqChannelModelId = Model.Id }, "dataTableEqWarning").AddColumn("Id")
                                        .AddColumn("Read_no")
                                        .AddColumn("Equipment_id_Text")
                                        .AddColumn("Io_real_value")
                                        .AddColumn("Io_input_value")
                                        .AddColumn("Lower_limit")
                                        .AddColumn("Upper_limit")
                                        .AddColumn("Warning_type_Text")
                                        .AddCustomJavascriptColumn("Active", " return full.Active ? \"<i class='fa fa-check' style='font-size: 18pt;color:green' />\" : \"<i class='fa fa-times' style='font-size: 18pt;color:red' /> \" ")
                                        //.AddColumn("Description")
                                        .AddColumn("Last_stop_datetime")
    .AddCustomJavascriptColumn("", "return getDatatableEditDeleteButtonString('" + @Url.Action("EditEqWarning", "EqChannel") + "/' + full.Id , full.Id, true,  true, 'EqWarning') ;")
    .SetLanguageUrl(WorkContext.WorkingLanguage.Id == 1 ? "~/Content/assets/global/plugins/datatables/turkish.json" : null)
    .SetLenghtMenu("5,10,50,100")
    .AddAttribute("'deferLoading' : 0")
    .AddAttribute("'responsive' : false ") @* DataTableResponsiveAttribute *@
    .AddAttribute("'scrollX' : true ")
    .AddAttribute("'buttons' :  DataTablePrintButtonAttribute  ")
    .Initialize());
    
    window.dataTableEqWarningOptions = dataTableEqWarningOptions;

                 $('#btnFilterEqWarning').click(function () {
                        dataTableEqWarning.column('Read_no:name').search($('#Read_no').val().trim());
                        dataTableEqWarning.column('Equipment_id:name').search($('#Equipment_id').val().trim());
                        dataTableEqWarning.column('Warning_type:name').search($('#Warning_type').val().trim());
                        dataTableEqWarning.column('Active:name').search($('#Active').prop('checked'));
                        dataTableEqWarning.column('Last_stop_datetime:name').search($('#Last_stop_datetime').val().trim());
                    //Apply search for Employee Name // DataTable column index 0
                   // dataTable.columns(0).search($('#txtEmployeeName').val().trim());
                    //Apply search for Country // DataTable column index 3
                    //dataTable.columns(0).search($('#ddCountry').val().trim());

                    //hit search on server
                dataTableEqWarning.draw();
            });
            
            
                $('#btnResetEqWarning').click(function () {

                    resetDatatableSearch('dataTableEqWarning');

                });


        
     
    
 
       setTimeout(function(){
        $('a[href="#tab_EqChannel_@Model.SelectedTab"]').tab('show');
        }, 500);

     $("#QuestionList").select2({multiple: true });
 
}

@section beforeFooter{

    <script type="text/javascript" src="~/Scripts/pages/EqChannel-input-mask.js"></script>
}

AssetHealth/Views/EqChannel/EditEqThreshold.cshtml
@using AssetHealth.Models.Eq_threshold;
@model EqThresholdModel

@{
    Layout = Request.IsAjaxRequest() ? "" : "~/Views/Shared/_ColumnsThree.cshtml";
    //page title
    ViewBag.Title = T("Admin.EqThreshold.EditEqThresholdDetails").Text;
}
@using (Html.BeginForm("EditEqThreshold", "EqChannel", FormMethod.Post))
{
    <div class="row">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-customers.png")" alt="" />
            @T("Admin.EqThreshold.EditEqThresholdDetails") - @Model.Name
            @Html.ActionLink("(" + T("Admin.Common.BackToList") + ")", "Edit/" + Request.QueryString["EqChannelModelId"])
        </div>
        <div class="pull-right" style="margin-right:25px;">
            <button type="submit" name="save" class="btn green">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            &nbsp;
            <a class="btn red" data-toggle="modal" data-id="@Model.Id" data-id="@Model.Id" data-deleteurl="@Url.Action("DeleteEqThreshold", new {Id = Model.Id})" href="#modalDeleteConfirm">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </a>
            
        </div>
    </div>
    <br />
    @Html.Partial("CreateOrUpdateEqThreshold", Model)
}

 
 @section jQueryOnReadyScripts {
 
        
 
       setTimeout(function(){
        $('a[href="#tab_EqThreshold_@Model.SelectedTab"]').tab('show');
        }, 500);
 
}

@section beforeFooter{

    <script type="text/javascript" src="~/Scripts/pages/EqThreshold-input-mask.js"></script>
}

AssetHealth/Views/EqChannel/EditEqWarning.cshtml
@using AssetHealth.Models.Eq_warning;
@model EqWarningModel

@{
    Layout = Request.IsAjaxRequest() ? "" : "~/Views/Shared/_ColumnsThree.cshtml";
    //page title
    ViewBag.Title = T("Admin.EqWarning.EditEqWarningDetails").Text;
}
@using (Html.BeginForm("EditEqWarning", "EqChannel", FormMethod.Post))
{
    <div class="row">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-customers.png")" alt="" />
            @T("Admin.EqWarning.EditEqWarningDetails") - @Model.LocationName
            @Html.ActionLink("(" + T("Admin.Common.BackToList") + ")", "Edit/" + Request.QueryString["EqChannelModelId"])
        </div>
        <div class="pull-right" style="margin-right:25px;">
            <button type="submit" name="save" class="btn green">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            &nbsp;
            <a class="btn red" data-toggle="modal" data-id="@Model.Id" data-id="@Model.Id" data-deleteurl="@Url.Action("DeleteEqWarning", new {Id = Model.Id})" href="#modalDeleteConfirm">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </a>
            
        </div>
    </div>
    <br />
    @Html.Partial("CreateOrUpdateEqWarning", Model)
}

 
 @section jQueryOnReadyScripts {
 
        
 
       setTimeout(function(){
        $('a[href="#tab_EqWarning_@Model.SelectedTab"]').tab('show');
        }, 500);
 
}

@section beforeFooter{

    <script type="text/javascript" src="~/Scripts/pages/EqWarning-input-mask.js"></script>
}